### ISSUE TITLE
Wong moves

### ISSUE THREAD

**Issue by sana2024** [softwerks/backgammon#1]
Hi,
i did everything the readme says and copied the exact code to google colad but it gives me a different result than the one is showing

as you see here i gave it 4OvgATDgc+QBUA as postion ID and cInpAAAAAAAA as match ID but the result moves checker from bar to point 21 with dice 3 instead to 22
![Screen Shot 2023-06-07 at 8 31 59 AM](https://github.com/softwerks/backgammon/assets/53705282/e36caea1-a62b-4998-9409-ed721a4f7163)

is there any extra step i need to do? or something i missed ???
i really appreciate your help.

**Comment by sambeirne** [comment]
I neglected to update [README.rst](https://github.com/softwerks/backgammon/blob/main/README.rst) after [commit 857a666](https://github.com/softwerks/backgammon/commit/857a666a5ee3b6ce70777d8359881092c087d5b9). That commit switched from point values (1, 2, 3...24) to a zero based index (0, 1, 2, 3...23). So, board_points[21] is point 22 on the board.

I updated [README.rst](https://github.com/softwerks/backgammon/blob/main/README.rst).
